### PR TITLE
Add destroyCursor for mouse

### PR DESCRIPTION
**Pull request by jordan4ibanez**
Maybe you want to do something crazy like have a dynamic cursor or generate cursors based on things that are happening?

This would be useful to stop a huge memory leak from happening. :)

### CODE REVIEW

**Comment by bjornbytes** [comment]
This is a good idea.  I think we should use `ffi.gc` for this though, so they will get cleaned up automatically.  To do this, the newCursor code would change to something like this:

```lua
return ffi.gc(C.glfwCreateCursor(image, hotx or 0, hoty or 0), C.glfwDestroyCursor)
```

(And same for getSystemCursor)

**Comment by jordan4ibanez** [comment]
I will do some research into this and let you know how it goes

**Comment by jordan4ibanez** [comment]
It works :)

**Comment by jordan4ibanez** [comment]
Should the ``getSystemCursor`` also use this GC functionality?

**Comment by jordan4ibanez** [comment]
Manual memory management has now been replaced with GC in commit 2

**Comment by bjornbytes** [comment]
Looks good, thanks for the PR!

**Comment by jordan4ibanez** [comment]
You're very welcome!

**Pull request merged**
